apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: bank-of-anthos
    environment: development
    team: stock-api
    tier: backend
  name: stock-api
  namespace: group4-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-api
      application: bank-of-anthos
      environment: development
      team: stock-api
      tier: backend
  template:
    metadata:
      labels:
        app: stock-api
        application: bank-of-anthos
        environment: development
        team: stock-api
        tier: backend
    spec:
      containers:
        - name: stock-api
          image: us-central1-docker.pkg.dev/dreamdev-team4/group4-repo/stock-api:placeholder
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://35.223.9.138:5432/stock-db
            - name: SPRING_DATASOURCE_USERNAME
              value: stockuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: stockpass
            - name: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
              value: "600000" # 600 seconds
            - name: SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT
              value: "600000"
            - name: SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT
              value: "50000"
#            - name: APP_MARKETSTACK_API_KEY
#              valueFrom:
#                secretKeyRef:
#                  name: marketstack-secret
#                  key: api-key
          ports:
            - containerPort: 8082
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: bank-of-anthos
    environment: development
    team: stock-api
    tier: backend
  name: stock-api
  namespace: group4-ns
spec:
  ports:
    - port: 8082
  selector:
    app: stock-api
    application: bank-of-anthos
    environment: development
    team: stock-api
    tier: backend
  type: LoadBalancer
